apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spherical-mammoth.fullname" . }}-secrets
  labels:
    {{- include "spherical-mammoth.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
  mammoth-postgres-password: {{ required "secrets.mammothPostgresPassword is required" .Values.secrets.mammothPostgresPassword | quote }}
  webhook-signing-secret: {{ required "secrets.webhookSigningSecret is required" .Values.secrets.webhookSigningSecret | quote }}
